ParselTongue/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('chat.urls')),
]

chat/urls.py
from django.contrib.auth.views import logout
from django.urls import path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('chat', views.chat_view, name='chats'),
    path('chat/<int:sender>/<int:receiver>', views.message_view, name='chat'),
    path('api/messages/<int:sender>/<int:receiver>', views.message_list, name='message-detail'),
    path('api/messages', views.message_list, name='message-list'),
    path('api/users/<int:pk>', views.user_list, name='user-detail'),
    path('api/users', views.user_list, name='user-list'),
    path('logout', logout, {'next_page': 'index'}, name='logout'),
    path('register', views.register_view, name='register'),
    path('group', views.gchat_view, name='groups'),
    path('group/<int:sender>/<int:room>', views.gmessage_view, name='group'),
    path('api/gmessages/<int:sender>/<int:room>', views.gmessage_list, name='gmessage-detail'),
    path('api/gmessages', views.gmessage_list, name='gmessage-list'),
    path('api/rooms/<int:pk>', views.room_list, name='room-detail'),
    path('api/rooms/', views.room_list, name='room-list'),
]

chat/models.py
from django.contrib.auth.models import User
from django.db import models

class Room(models.Model):
    room = models.CharField(max_length=1200)
    def __str__(self):
        return self.room
    class Meta:
        ordering = ('room',)

class Message(models.Model):
     sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
     receiver = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receiver')
     message = models.CharField(max_length=1200)
     timestamp = models.DateTimeField(auto_now_add=True)
     is_read = models.BooleanField(default=False)
     def __str__(self):
           return self.message
     class Meta:
           ordering = ('timestamp',)

class GroupMessage(models.Model):
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='%(class)s_sender')
    room = models.ForeignKey(Room, on_delete=models.CASCADE, related_name='room_id')
    message = models.CharField(max_length=1200)
    timestamp = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)
    def __str__(self):
        return self.message
    class Meta:
        ordering = ('timestamp',)

chat/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.http.response import JsonResponse, HttpResponse
from django.shortcuts import render, redirect
from django.views.decorators.csrf import csrf_exempt
from rest_framework.parsers import JSONParser
from chat.models import Message, GroupMessage, Room
from chat.serializers import MessageSerializer, UserSerializer, GroupSerializer, RoomSerializer
from django.contrib import messages

def index(request):
    if request.user.is_authenticated:
        return redirect('chats')
    if request.method == 'GET':
        return render(request, 'chat/index.html', {})
    if request.method == "POST":
        username, password = request.POST['username'], request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
        else:
            messages.error(request,'Username/Password combination incorrect!')
            return redirect('index')
        return redirect('chats')

@csrf_exempt
def user_list(request, pk=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        if pk:
            users = User.objects.filter(id=pk)
        else:
            users = User.objects.all()
        serializer = UserSerializer(users, many=True, context={'request': request})
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = UserSerializer(data=data)
        if serializer.is_valid():
            serializer.create(serializer.validated_data)
            #serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

def register_view(request):
    """
    Render registration template
    """
    if request.user.is_authenticated:
        return redirect('chats')
    return render(request, 'chat/register.html', {})


def chat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat.html',
                      {'users': User.objects.exclude(username=request.user.username),
                       'rooms': Room.objects.all()})

@csrf_exempt
def message_list(request, sender=None, receiver=None):
    """
    List all required messages, or create a new message.
    """
    if request.method == 'GET':
        messages = Message.objects.filter(sender_id=sender, receiver_id=receiver, is_read=False)
        serializer = MessageSerializer(messages, many=True, context={'request': request})
        for message in messages:
            message.is_read = True
            message.save()
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = MessageSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

def message_view(request, sender, receiver):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, "chat/messages.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'rooms': Room.objects.all(),
                       'receiver': User.objects.get(id=receiver),
                       'messages': Message.objects.filter(sender_id=sender, receiver_id=receiver) |
                                   Message.objects.filter(sender_id=receiver, receiver_id=sender)})

@csrf_exempt
def room_list(request, pk=None):
    if request.method == 'GET':
        if pk:
            rooms = Room.objects.filter(id=pk)
        else:
            rooms = Room.objects.all()
        serializer = RoomSerializer(rooms, many=True, context={'request': request})
        return JsonResponse(serializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        serializer = RoomSerializer(data=data)
        if serializer.is_valid():
            serializer.save()
            return JsonResponse(serializer.data, status=201)
        return JsonResponse(serializer.errors, status=400)

def gchat_view(request):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, 'chat/chat.html',
                      {'rooms': Room.objects.all()})

@csrf_exempt
def gmessage_list(request, sender=None, room=None):
    if request.method == 'GET':
        gmessages = GroupMessage.objects.filter(room_id=room, is_read=False)
        gserializer = GroupSerializer(gmessages, many=True, context={'request': request})
        for gmessage in gmessages:
            gmessage.is_read = True
            gmessage.save()
        return JsonResponse(gserializer.data, safe=False)

    elif request.method == 'POST':
        data = JSONParser().parse(request)
        gserializer = GroupSerializer(data=data)
        if gserializer.is_valid():
            gserializer.save()
            return JsonResponse(gserializer.data, status=201)
        return JsonResponse(gserializer.errors, status=400)

def gmessage_view(request, sender, room):
    if not request.user.is_authenticated:
        return redirect('index')
    if request.method == "GET":
        return render(request, "chat/group.html",
                      {'users': User.objects.exclude(username=request.user.username),
                       'rooms': Room.objects.all(),
                       'receiver': Room.objects.get(id=room),
                       'gmessages': GroupMessage.objects.filter(room_id=room)})

templates/chat/chat.html
{% extends 'chat/index.html' %}
{% block body %}
<nav class="blue lighten-3">
    <div class="nav-wrapper container">
      <a href="#" class="brand-logo">MACChat</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><a href="">{{ request.user.username }}</a></li>
          <li><a href="{% url 'logout' %}"><i class="material-icons">power_settings_new</i></a></li>
      </ul>
    </div>
</nav>
    <div class="section" style="height: 80vh">
    <div class="row">
        <div class="col s3">
        <div class="card">
            <div class="collection">
                {% for user in users %}
                <a href="{% url 'chat' request.user.id user.id %}" id="user{{ user.id }}" class="collection-item row">
                    <img src="https://frontend-1.adjust.com/new-assets/images/site-images/interface/user.svg" class="col s4">
                    <div class="col s8">
                    <span class="title" style="font-weight: bolder">{{ user.username }}</span>
                    </div>
                </a>
                {% endfor %}
            </div>
        </div>
        </div>
        <div class="col s9">
            <div class="card">
            <div id="board" class="section grey lighten-3" style="height: 68vh; padding: 5px; overflow-y: scroll">
                {% block messages %}

                {% endblock %}
            </div>
            <form id="chat-box" class="form-group {% block hide %}hide{% endblock %}" method="post">
                {% csrf_token %}
                <div class="row">
                    <div class="col s11">
                        <div class="input-field">
                            <input id="id_message" name="message" type="text" placeholder="Type your message..">
                        </div>
                    </div>
                    <div class="col s1" style="line-height: 80px">
                        <button class="btn btn-floating blue lighten-2 waves-effect waves-light"><i class="material-icons">send</i></button>
                    </div>
                </div>
            </form>
            </div>
        </div>
    </div>
    </div>
    {% load staticfiles %}
    <script src="{% static 'js/chat.js' %}"></script>
    <script>
        // For receiving
        sender_id = "{{ receiver.id }}";
        receiver_id = "{{ request.user.id }}";

        //For sending
        $(function () {
            scrolltoend();
            $('#chat-box').on('submit', function (event) {
                event.preventDefault();
                var message = $('#id_message');
                send('{{ request.user.username }}', '{{ receiver.username }}', message.val());
                message.val('');
            })
        })
    </script>
{% endblock %}

templates/chat/group.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block gmessages %}
    {% for gmessage in gmessages %}
        {% if gmessage.sender == request.user %}
            <div class="card-panel right" style="width: 75%; position: relative">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
                <div style="position: absolute; top: 0; right:3px; font-weight: lighter">{{ gmessage.timestamp }}</div>
                {{ gmessage }}
            </div>
        {% else %}
            <div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
                <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ gmessage.sender }}</div>
                <div style="position: absolute; top: 0; right:3px; font-weight: lighter">{{ gmessage.timestamp }}</div>
                {{ gmessage }}
            </div>
        {% endif %}
        {% empty %}
            <div id="no_rooms">
                <span class="title" style="font-weight: bolder">No messages in chatroom yet.</span>
            </div>
    {% endfor %}
<script>
    //For sending
    // Send takes three args: sender, room, message. sender & room are ids of users and the room, and message is the text to be sent.
    function gsend(sender, room, message) {
        console.log(sender);
        console.log(room);
        console.log(message);
        //POST to '/api/messages', the data in JSON string format
        $.post('/api/gmessages', '{"sender": "'+ sender +'", "room": "'+ room +'","message": "'+ message +'" }', function (data) {
            console.log(data);
            var box = text_box.replace('{sender}', "You"); // Replace the text '{sender}' with 'You'
            box = box.replace('{message}', message); // Replace the text '{message}' with the message that has been sent.
            $('#board').append(box); // Render the message inside the chat-box by appending it at the end.
            scrolltoend(); // Scroll to the bottom of he chat-box
        })
    }

    $(function () {
        scrolltoend();
        $('#chat-box').on('submit', function (event) {
            event.preventDefault();
            var gmessage = $('#id_message');
            gsend('{{ request.user.username }}', '{{ receiver }}', gmessage.val());
            gmessage.val('');
        })
    })

    //For receiving
    function greceive() {
        // 'sender_id' and 'receiver_id' are global variable declared in the chat.html, which contains the ids of the user / room
        $.get('/api/gmessages/'+ sender_id + '/' + receiver_id, function (data) {
            console.log(data);
            if (data.length !== 0)
            {
                for(var i=0;i<data.length;i++) {
                    console.log(data[i]);
                    var box = text_box.replace('{sender}', data[i].sender);
                    box = box.replace('{message}', data[i].message);
                    box = box.replace('right', 'left blue lighten-5');
                    $('#board').append(box);
                    scrolltoend();
                }
            }
        })
    }

    $(function () {
        $('#room{{ receiver.id }}').addClass('active');
        //Call receive function each 1 seconds to check for new messages in the database
        setInterval(greceive,1000)
    })
</script>
{% endblock %}

templates/chat/index.html
{% load staticfiles %}
  <!DOCTYPE html>
  <html>
    <head>
      <!--Import Google Icon Font-->
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <link type="text/css" rel="stylesheet" href="{% static 'css/materialize.min.css' %}"  media="screen,projection"/>
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}"  media="screen,projection"/>

      <!--Let browser know website is optimized for mobile-->
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <!--Import jQuery before materialize.js-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
        <script type="text/javascript" src="{% static 'js/materialize.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/chat.js' %}"></script>
    </head>

    <body>
    {% block body %}
        <div class="section blue lighten-3">
            <div class ="chip">
                <img src="{% static 'images/logo2.png' %}" class="white">
                MACChat
            </div>
        </div>
        <div class="container">
            <div class="row">
            <div class="col s12 m8 l6 offset-m2 offset-l3">
                <div class="section center-block">
                <div>
                    {% block form %}
                    <h3>
                    Login
                    </h3>
                    <form id="login-form" class="form-group" method="post">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="username" id="id_username" type="text">
                                <label for="id_username">Username</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="input-field col s12">
                                <input name="password" id="id_password" type="password">
                                <label for="id_password">Password</label>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col s8">
                                <a href="{% url 'register' %}">Register</a>
                            </div>
                            <div class="col s4">
                            <div class="right">
                                <button class="btn blue waves-effect waves-light pull-s12">Login</button>
                            </div>
                            </div>
                        </div>
                    </form>
                    {% endblock %}
                </div>
            </div>
            </div>
            </div>
        </div>
        {% endblock %}
    </body>

  </html>

templates/chat/messages.html
{% extends 'chat/chat.html' %}
{% block hide %}{% endblock %}
{% block messages %}
    {% for message in messages %}
    {% if message.sender == request.user %}
<div class="card-panel right" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">You</div>
    {{ message }}
</div>
    {% else %}
<div class="card-panel left blue lighten-5" style="width: 75%; position: relative">
    <div style="position: absolute; top: 0; left:3px; font-weight: bolder" class="title">{{ message.sender }}</div>
    {{ message }}
</div>
    {% endif %}
    {% endfor %}
<script>
$(function () {
    $('#user{{ receiver.id }}').addClass('active');
    //Call receive function each 1 seconds to check for new messages in the database
    setInterval(receive,1000)
})
</script>
{% endblock %}

templates/chat/register.html
{% extends 'chat/index.html' %}
{% block form %}
    <h3>
    Register
    </h3>
    <form id="register-form" class="form-group">
        {% csrf_token %}
        <div class="row">
            <div class="input-field col s12">
                <input name="username" id="id_username" type="text" class="validate">
                <label for="id_username" data-error="Username already taken">Username</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password" id="id_password" type="password">
                <label for="id_password">Password</label>
            </div>
        </div>
        <div class="row">
            <div class="input-field col s12">
                <input name="password2" id="id_password2" type="password">
                <label for="id_password2">Repeat Password</label>
            </div>
        </div>
        <div class="row">
            <div class="col s12">
            <div class="right">
                <button class="btn blue waves-effect waves-light pull-s12">Register</button>
            </div>
            </div>
        </div>
    </form>
    <script>
    $(function () {
        $('#register-form').on('submit', function (event) {
            event.preventDefault();
            var username = $('#id_username').val();
            var password;
            if(username !== '')
            {
                password = $('#id_password').val();
                if(password !== '' && password === $('#id_password2').val()){
                    register(username, password);
                }
                else{
                    alert("The passwords doesn't match!");
                }
            }
            else
                alert("Please enter a valid username!");
        })
    })
    </script>
{% endblock %}